"""Canonical evidence checklists per control.

These are framework-version-stable suggestions an auditor would typically
ask for. Each control aims to cover the five evidence layers:
  1. Documentation  (policy / procedure / standard / charter)
  2. Implementation (system config, screenshots, ticket samples, exports)
  3. Operational    (logs, audit trail, records of executed actions)
  4. Review         (periodic recertifications, sign-offs, exception register)
  5. Metrics        (KPI/KRI dashboards or counts) — where applicable

Keyed by `(framework_urn, ref_id)` → `list[str]`. The seed loader will
OVERWRITE typical_evidence on every startup for built-in frameworks
(matched by urn in BUILT_IN_EVIDENCE_HINTS), so admins can push checklist
updates simply by editing this file and redeploying.

Custom user-imported frameworks (urn not in this dict) are NOT touched.
"""

# ---------------------------------------------------------------------------
# ISO/IEC 27001:2022 Annex A — implementation guidance drawn from ISO 27002:2022
# ---------------------------------------------------------------------------

ISO_27001_2022_EVIDENCE: dict[str, list[str]] = {
    # A.5 Organizational controls --------------------------------------------
    "A.5.1": [
        "Approved Information Security Policy (PDF/Confluence) with version, effective date, and CISO/board approver",
        "Topic-specific policies (Access Control, Acceptable Use, Cryptography, BCP, Incident, Data Protection, Supplier, …) with changelog",
        "Policy hierarchy diagram showing how topic policies map to the master policy",
        "Annual policy review record and Management Review minutes signing off on review outcome",
        "Communication evidence: training register, all-hands deck, intranet announcement, email blast log",
        "Acknowledgement records — each employee accepting the policy on hire and at annual renewal",
        "Exception register: approved deviations, owner, expiry date, compensating controls",
    ],
    "A.5.2": [
        "RACI matrix mapping every security responsibility to a named role/team",
        "Job descriptions for CISO, Security Manager, control owners, incident commanders",
        "Org chart showing reporting line for the security function (to CEO/board)",
        "Security committee charter with membership, cadence, decision rights",
        "Last 3 committee meeting minutes evidencing oversight",
        "Performance objectives for security leadership tied to KPI/KRI outcomes",
    ],
    "A.5.3": [
        "List of incompatible duty pairs (developer↔prod deployer, requester↔approver, etc.)",
        "Access-control matrix showing role separations enforced in IAM / PAM tooling",
        "Compensating-control register where SoD cannot be enforced (with monitoring evidence)",
        "Periodic SoD conflict-detection scan results (manual or via tools like SailPoint, Saviynt)",
        "Sample tickets showing dual-approval workflows for high-risk changes",
    ],
    "A.5.4": [
        "ISMS scope statement signed by senior management",
        "Management Review minutes covering security KPIs, incidents, risks, audit findings",
        "Documented management commitment letter / policy preamble",
        "Resource allocation evidence — approved security budget, headcount plan",
        "Top-down communication of security priorities (memos, town-hall slides)",
    ],
    "A.5.5": [
        "Contact list with regulators, national CERT/CSIRT, law-enforcement liaison",
        "SOP for engaging authorities during a reportable incident",
        "Evidence of past contact (anonymised) — coordination ticket or letter",
        "Calendar of mandatory reporting deadlines (GDPR 72h, NIS2, sector-specific)",
        "Verified contact details refreshed in the last 12 months",
    ],
    "A.5.6": [
        "Memberships in security ISACs / industry forums (FIRST, ISACA, OWASP, sector ISAC)",
        "Threat-intel feed subscriptions list with renewal dates",
        "Conference / training attendance records (last 12 months)",
        "Internal briefing notes summarising intel takeaways for the team",
        "Documented liaison roles (who attends which forum)",
    ],
    "A.5.7": [
        "Threat-intel platform configuration (MISP, ThreatConnect, Recorded Future)",
        "TI feed inventory (OSINT + commercial) with refresh frequency",
        "Sample periodic intel-briefing report disseminated internally",
        "Documented intel-to-control feedback loop (intel → detection rule)",
        "Detection rules or blocklists traceable to specific TI inputs",
        "Quarterly threat-landscape report consumed by leadership",
    ],
    "A.5.8": [
        "Project intake form requiring a mandatory security risk question",
        "Sample project plan showing security checkpoints / gates",
        "Architecture / threat-model artefact for an in-flight project",
        "Security sign-off record at major milestones (design, pre-launch)",
        "Security exception requests raised by project teams (and outcomes)",
    ],
    "A.5.9": [
        "Asset inventory export (CMDB / spreadsheet) with owner, classification, location, criticality",
        "Reconciliation report (CMDB vs network scan vs MDM)",
        "Inventory update SOP (when to register, when to retire)",
        "Quarterly reconciliation review minutes",
        "Sample asset-decommissioning records",
        "Coverage metric (% of assets with owner + classification populated)",
    ],
    "A.5.10": [
        "Acceptable Use Policy (AUP) with version",
        "Signed AUP acknowledgements per user",
        "Onboarding training completion records covering AUP",
        "Sample monitoring / enforcement records (e.g. CASB alert on policy breach)",
        "Periodic AUP refresher training",
    ],
    "A.5.11": [
        "Offboarding checklist with asset-return step",
        "Sample completed offboarding tickets (last 5 leavers)",
        "Asset-return form template and signed instances",
        "MDM wipe / decommissioning log",
        "Reconciliation report showing returned vs issued assets per quarter",
    ],
    "A.5.12": [
        "Data classification scheme (e.g. Public / Internal / Confidential / Restricted) doc",
        "Decision tree / examples mapping data types to classification",
        "List of authoritative data assets with assigned classification",
        "Training material covering classification handling",
        "Periodic re-classification review for high-value datasets",
    ],
    "A.5.13": [
        "Labelling standard (header/footer templates, file-name conventions, watermarks, tags)",
        "Sample classified documents demonstrating labels in use",
        "Configuration of automated classification tools (Microsoft Purview, Titus, Boldon James)",
        "Data-tag enforcement on cloud storage (e.g. S3 object tags, GCS labels)",
        "Audit log showing classification applied at creation",
    ],
    "A.5.14": [
        "Secure-transfer SOP listing approved channels (SFTP, MFT, encrypted email, secure portals)",
        "Configuration / logs of MFT or DLP showing enforcement",
        "Encryption-at-transit verification (TLS-only enforcement, SSL Labs scan)",
        "Procedure for ad-hoc transfers and recipient verification",
        "Audit-log sample showing tracked transfers of confidential data",
    ],
    "A.5.15": [
        "Access Control Policy (versioned)",
        "Role-to-permission matrix per critical system",
        "Joiner/Mover/Leaver workflow evidence (tickets, screenshots)",
        "PAM / IAM tool configuration screenshots",
        "Quarterly access recertification report with owner sign-off",
        "Same-day termination revocation evidence (audit log)",
        "Privileged access logs for last 90 days",
        "Standing-access vs just-in-time elevation metrics",
    ],
    "A.5.16": [
        "Identity lifecycle SOP (create / amend / disable / delete)",
        "Identity store inventory (AD, Okta, Azure AD, AWS IAM, GCP IAM, …)",
        "Unique-ID enforcement evidence (no shared accounts; or compensating controls)",
        "Service-account inventory with owner + purpose",
        "Stale-account audit report (accounts not used in 90 days)",
        "De-duplication evidence across identity stores",
    ],
    "A.5.17": [
        "Authentication policy (password length/complexity, rotation, MFA requirements)",
        "Secrets-manager configuration (Vault, AWS Secrets Manager, 1Password Business) screenshots",
        "Initial-credential delivery SOP (out-of-band, one-time)",
        "Failed-login alerting configuration",
        "Audit log of credential changes / resets",
        "Compromised-credential monitoring (HIBP / breach intel) configuration",
    ],
    "A.5.18": [
        "Provisioning workflow with documented approvers per system",
        "Least-privilege guideline mapping roles → minimum permissions",
        "Privileged-role allow-list and access-request tickets sample",
        "Quarterly access-recertification campaigns and outcomes",
        "Termination-day revocation evidence (HR-trigger → IAM)",
        "Emergency / break-glass account procedure and last-use review",
        "Access reconciliation report between HR system and IAM",
    ],
    "A.5.19": [
        "Supplier security policy and risk-tiering rubric",
        "Vendor inventory with criticality / data-access tier",
        "Vendor onboarding due-diligence checklist (questionnaire + cert review)",
        "Sample completed vendor security review",
        "List of critical suppliers + last assessment date",
        "Periodic vendor risk-review meeting minutes",
    ],
    "A.5.20": [
        "Template DPA / Security Addendum / DPAg for vendor contracts",
        "Sample executed contract containing security clauses (redacted)",
        "Standard security exhibit covering encryption, breach notification, audit rights",
        "Contract review checklist with security signoff",
        "Renewal-tracker showing security-clause refresh per renewal",
    ],
    "A.5.21": [
        "Supply-chain security requirements doc (SBOM, code-signing, secure delivery)",
        "Vendor SBOM (CycloneDX/SPDX) for a critical product",
        "Procurement-stage component scanning evidence (e.g. dependency-track)",
        "Software-signing verification SOP",
        "Hardware authenticity verification SOP (anti-counterfeit, secure shipping)",
        "Sub-supplier (4th-party) inventory for top vendors",
    ],
    "A.5.22": [
        "Annual / per-renewal vendor performance + security review report",
        "Change-management evidence when a key supplier changes (M&A, sub-contractor change)",
        "Continuous-monitoring data (SecurityScorecard / BitSight / similar)",
        "Vendor breach-disclosure SOP and example notifications received",
        "Trend report over multiple periods showing risk movement",
    ],
    "A.5.23": [
        "Cloud-usage register (CSPs, services, account IDs, owners, criticality, data classes)",
        "Shared-responsibility matrix per CSP",
        "Cloud security baselines (CIS Benchmarks, AWS Foundational SBP, CSA CCM)",
        "CSPM tool output (Wiz / Prisma Cloud / native scanners) for current period",
        "IAM-baseline scanning evidence (IAM Access Analyzer, Steampipe queries)",
        "Cloud incident-response playbooks per CSP",
    ],
    "A.5.24": [
        "Incident Response Plan with severity matrix, roles, RACI",
        "Communication tree / on-call rota / paging integration",
        "Tabletop exercise report (within last 12 months)",
        "IR training records for the IR team",
        "Incident classification taxonomy doc",
        "Tooling readiness: SIEM, EDR, ticketing, evidence-collection agents",
    ],
    "A.5.25": [
        "Triage SOP and severity decision tree",
        "Sample event records showing severity classification + rationale",
        "First-responder runbooks per detection category",
        "Decision criteria for escalation vs closure of an event",
        "Quality-review sample (e.g. last 20 alerts re-checked for accuracy)",
    ],
    "A.5.26": [
        "Sample incident post-mortems (last 12 months) with timeline + actions",
        "After-action review meeting minutes",
        "Containment playbooks per incident type",
        "Recovery / eradication SOPs (rebuild, credential reset)",
        "Communication templates used during incidents",
        "Evidence-collection / forensic preservation log per incident",
    ],
    "A.5.27": [
        "Lessons-learned register with action owners + status",
        "Detection-rule / process changes traceable to past incidents",
        "Trend analysis (incident counts / categories / MTTR over time)",
        "Annual incident retrospective deck for leadership",
        "Procedure for updating IRP after lessons learned",
    ],
    "A.5.28": [
        "Forensic evidence-handling SOP (chain of custody, hashing, packaging)",
        "Sample evidence custody form (completed, redacted)",
        "Forensic workstation / image-acquisition tool inventory",
        "Logs of past evidence collections (case ID, custodian, hash)",
        "Training records for forensic responders",
    ],
    "A.5.29": [
        "Business continuity plan covering security responsibilities during disruption",
        "Last BCP test report with scenarios and findings",
        "RTO/RPO matrix per business service",
        "Crisis-management team contact list",
        "Communication plan for impaired-operations periods",
    ],
    "A.5.30": [
        "ICT continuity strategy with RTO/RPO per system",
        "DR architecture diagrams (warm / hot standby, multi-region)",
        "DR test report with restore evidence (system, data, time)",
        "Runbooks for failover and failback",
        "Last test of out-of-band communication channels",
    ],
    "A.5.31": [
        "Register of applicable laws / regulations / contracts (GDPR, HIPAA, NIS2, SOC2, …)",
        "Mapping of each requirement to controls / policies / owners",
        "Privacy notice / customer-facing legal commitments",
        "Last legal review evidence",
        "Compliance-monitoring dashboard showing applicable obligations",
    ],
    "A.5.32": [
        "IP policy (open-source usage, code-licence scanning, contributor agreements)",
        "OSS scanner output (FOSSA, Black Duck, Snyk Licence) for production builds",
        "Software inventory annotated with licence type",
        "DMCA / takedown procedure",
        "License approval workflow for new OSS adoption",
    ],
    "A.5.33": [
        "Record-retention schedule per data type",
        "Backup configuration evidence for records-of-record",
        "Tested-restore evidence (date + outcome)",
        "Legal-hold procedure and active-hold list",
        "Audit log immutability evidence (WORM storage, append-only logging)",
    ],
    "A.5.34": [
        "Privacy notice / DPIA template + recent DPIA artefacts",
        "Records of Processing Activities (RoPA, GDPR Art. 30)",
        "DSAR / Subject Rights Request handling SOP",
        "Data Protection Officer (DPO) appointment evidence",
        "Privacy training records for staff handling PII",
        "Data-residency / cross-border-transfer mechanism evidence (SCCs, DPF)",
    ],
    "A.5.35": [
        "Last independent security audit / pentest report + remediation plan",
        "Internal-audit programme schedule covering security",
        "Audit committee minutes covering security findings",
        "Open audit-findings tracker with target dates",
        "Sample closed findings with verification evidence",
    ],
    "A.5.36": [
        "Compliance monitoring dashboard (control owners, last-checked dates)",
        "Exception register with approved expiry dates + compensating controls",
        "Quarterly compliance review report",
        "Self-attestation by control owners (annual)",
        "Sample non-conformity records and corrective actions",
    ],
    "A.5.37": [
        "Operational runbooks for critical security functions (patching, backup, IR, monitoring)",
        "Runbook version-control evidence (git / Confluence history)",
        "Runbook approval / sign-off evidence",
        "Last runbook drill / dry-run for a critical procedure",
        "Coverage metric (% critical processes with runbooks)",
    ],

    # A.6 People controls -----------------------------------------------------
    "A.6.1": [
        "Background-check / screening procedure",
        "List of role tiers and required check levels (basic, enhanced, security-clearance)",
        "Sample completed BG check evidence (redacted)",
        "Periodic re-screening procedure for high-trust roles",
        "Service provider used for screening + their accreditation",
        "Coverage metric (% staff with valid screening on file)",
    ],
    "A.6.2": [
        "Employment contract template with confidentiality + security clauses",
        "Sample signed contract (redacted) — recent hire",
        "Contractor agreement template",
        "Code-of-conduct doc covering security expectations",
        "Tracking system showing signed contract on file per employee",
    ],
    "A.6.3": [
        "Annual security-awareness training completion report (per-user, per-team)",
        "Phishing simulation campaign results and trend over time",
        "Role-specific training (devs → secure coding; admins → privileged-access; finance → BEC) records",
        "Onboarding security induction completion log",
        "Training content samples / curriculum",
        "Effectiveness measure (e.g. click-rate trend, certificate quiz pass-rates)",
    ],
    "A.6.4": [
        "Disciplinary procedure document for policy violations",
        "Anonymised log of past disciplinary actions tied to security violations",
        "Sanctions matrix mapping violation severity → action",
        "HR-Security coordination procedure for handling violations",
        "Awareness of disciplinary process in employee handbook",
    ],
    "A.6.5": [
        "Offboarding SOP detailing post-termination security duties",
        "NDA template surviving employment",
        "Reminder communication template sent to leavers",
        "Audit log showing access termination at separation",
        "Last reconciliation: HR terminations vs IAM disabled accounts",
    ],
    "A.6.6": [
        "NDA / confidentiality template for staff and contractors",
        "Tracking system showing NDA-on-file per employee + contractor",
        "Vendor NDA register",
        "Procedure for revoking NDA-covered info access at separation",
        "Periodic NDA refresh for long-tenured roles",
    ],
    "A.6.7": [
        "Remote-work policy (device security, network, family environment, recording)",
        "MDM configuration enforcing remote-endpoint posture (encryption, screen-lock, EDR)",
        "VPN / ZTNA configuration for remote access",
        "Home-network minimum requirements doc",
        "Periodic remote-worker compliance scan",
        "Acceptable physical-environment guidance (lockable storage, shoulder-surfing)",
    ],
    "A.6.8": [
        "Internal reporting channels (ticket queue, security@, hotline) advertised to staff",
        "Sample submitted event reports and triage outcomes",
        "Anonymous reporting option (whistleblower hotline)",
        "Awareness material instructing employees how to report",
        "Metric: events reported per quarter, % triaged within SLA",
    ],

    # A.7 Physical controls --------------------------------------------------
    "A.7.1": [
        "Site plan showing physical security perimeters",
        "Specifications for fences, walls, doors, locks per zone",
        "Perimeter inspection / maintenance log",
        "Risk assessment for site choice",
        "Drawings highlighting datacentre / comms room placement",
    ],
    "A.7.2": [
        "Access-card / biometric system configuration screenshots",
        "Visitor management SOP and recent visitor log sample (anonymised)",
        "Pre-authorisation procedure for new badge issuance",
        "Periodic badge audit (active vs HR-on-roll)",
        "Tailgating prevention mechanisms (mantrap, anti-passback)",
        "CCTV coverage at every entry point",
    ],
    "A.7.3": [
        "Locked-zone listing (server rooms, comms rooms, restricted areas) + access list",
        "Access-list review evidence (monthly / quarterly)",
        "Door / cabinet lock standards",
        "Intrusion-detection sensor configuration",
        "Sample alarm investigation record",
    ],
    "A.7.4": [
        "CCTV retention policy and sample footage-retrieval log",
        "Intrusion-detection system status report",
        "Camera coverage diagram",
        "Sample alarm investigation tickets",
        "Periodic camera-health-check report",
    ],
    "A.7.5": [
        "Environmental risk assessment (fire, flood, earthquake, power)",
        "Fire-suppression certification + last test report",
        "Water-detection / leak-detection sensor configuration",
        "HVAC redundancy diagram",
        "Site insurance certificate covering environmental risks",
    ],
    "A.7.6": [
        "Secure-area work procedure (escorts, photo restriction, sign-in/out)",
        "Sample work permits / sign-in logs",
        "Approved tooling/device list for secure-area work",
        "Pre-work briefing record",
        "Post-work area-clearance check",
    ],
    "A.7.7": [
        "Clear-desk / clear-screen policy",
        "Walk-around audit report (sampling)",
        "Workstation auto-lock configuration (group policy / MDM)",
        "Secure-print / pull-print configuration",
        "Locker / secure-storage inventory in shared areas",
    ],
    "A.7.8": [
        "Server-room layout with rack siting, UPS, HVAC placement",
        "Last inspection / commissioning report",
        "Equipment grounding / bonding standards",
        "Anti-static measures evidence",
        "Cooling-capacity vs equipment-load report",
    ],
    "A.7.9": [
        "Off-premises asset register (laptops, mobile, leased gear)",
        "Insurance certificate covering off-site assets",
        "Travel-with-equipment SOP (encryption, transport security)",
        "Loss/theft reporting workflow + last 12-month incidents",
        "Remote-wipe configuration via MDM",
    ],
    "A.7.10": [
        "Removable-media policy",
        "DLP / EDR controls blocking USB write (config screenshots)",
        "Media inventory and disposal records",
        "Approval workflow for sanctioned removable media",
        "Periodic audit of USB usage logs",
    ],
    "A.7.11": [
        "UPS specifications + last load test report",
        "Power redundancy diagram (dual-feed, generator)",
        "HVAC / chilled-water service contracts and SLAs",
        "Backup-power fuel-supply contract",
        "Monitoring dashboard for utilities health",
    ],
    "A.7.12": [
        "Cable-management standard (segregation of power/data, labelling)",
        "Walk-through photos of cable rooms",
        "Cabling inspection / refresh schedule",
        "Tamper-evident sleeves on high-risk cable runs",
        "Fibre-vs-copper deployment rationale doc",
    ],
    "A.7.13": [
        "Hardware maintenance contracts + SLA",
        "Sample maintenance work-order records",
        "Approved-vendor list for on-site maintenance",
        "Pre/post-work security clearance for maintenance staff",
        "Asset-monitoring during third-party maintenance",
    ],
    "A.7.14": [
        "Secure-disposal SOP (data sanitisation method per media type)",
        "Last disposal vendor certificates (with serials)",
        "Internal degausser / shredder operational records",
        "Cross-verification (issued-for-disposal vs disposed)",
        "Sanitisation standard alignment (NIST SP 800-88, DoD 5220.22-M)",
    ],

    # A.8 Technological controls ---------------------------------------------
    "A.8.1": [
        "Endpoint protection policy (EDR, disk encryption, host firewall, screen-lock)",
        "MDM / EDR console screenshot showing fleet coverage",
        "Compliance metric: % endpoints patched, encrypted, EDR-active",
        "Baseline configuration (CIS, vendor STIG) per OS",
        "Mobile-device management policy and enrollment evidence",
        "BYOD policy (if applicable) and isolation mechanism",
        "Endpoint-incident sample (EDR alert → response)",
    ],
    "A.8.2": [
        "PAM tool configuration (CyberArk, BeyondTrust, AWS IAM admin roles)",
        "Privileged-session recording sample",
        "Just-in-time elevation workflow evidence",
        "Standing privileged-access inventory and rationale",
        "Break-glass account procedure and last-use audit",
        "Privileged-action audit logs (last 30 days)",
        "Quarterly privileged-access recertification",
    ],
    "A.8.3": [
        "Need-to-know matrix per data classification",
        "Access-review reports per quarter with sign-off",
        "Data-store ACL exports (databases, file shares, S3 buckets)",
        "Procedure for requesting / approving access",
        "Termination evidence (same-day access revocation)",
        "Compensating monitoring for shared accounts (where unavoidable)",
    ],
    "A.8.4": [
        "Source-control access policy (branch protection, code-owner files)",
        "Audit log showing repo access limited to project members",
        "Sample CODEOWNERS / branch-protection settings on a critical repo",
        "Build-artefact access control evidence",
        "Source-code review process doc",
        "Sample PR with mandatory reviewer approval",
    ],
    "A.8.5": [
        "MFA enforcement report (IdP screenshot showing 100% MFA coverage)",
        "Authentication policy (passwordless, FIDO2, SSO scope)",
        "Conditional-access policies (location, device posture, risk-based)",
        "Phishing-resistant MFA rollout plan / status",
        "Session-management configuration (timeout, re-auth on sensitive actions)",
        "Failed-auth alerting + sample triage",
    ],
    "A.8.6": [
        "Capacity-monitoring dashboard (CPU, memory, storage, network)",
        "Capacity forecast report",
        "Auto-scaling policies for cloud workloads",
        "Capacity-threshold alerting configuration",
        "Sample capacity-incident review",
    ],
    "A.8.7": [
        "EDR / AV deployment report (% coverage, signature freshness)",
        "Sample EDR alert + response evidence",
        "Anti-malware policy & exceptions register",
        "Email-gateway sandboxing configuration",
        "Web-gateway / DNS filtering configuration",
        "Quarantine / recovery procedure",
        "Effectiveness metric (malware blocked over time)",
    ],
    "A.8.8": [
        "Vulnerability scanner config (Nessus, Qualys, Wiz, Snyk)",
        "Last full-fleet scan report with severities",
        "Patch-management SLA + compliance metrics (P1 < 7d, P2 < 30d, …)",
        "Open vulnerability backlog with assignees and SLA status",
        "Risk-based prioritisation evidence (CVSS + EPSS + KEV)",
        "Exception register for unpatched-but-mitigated items",
        "Coordinated-disclosure / bug-bounty SOP",
    ],
    "A.8.9": [
        "Hardening standards (CIS Benchmarks, vendor STIGs) by OS / platform",
        "Configuration-baseline scanner output (CIS-CAT, AWS Config rules, Azure Policy)",
        "Drift-detection alerts and remediation tickets",
        "Golden-image / IaC-template repository",
        "Change-control evidence for baseline updates",
        "Coverage metric (% systems compliant with baseline)",
    ],
    "A.8.10": [
        "Data-deletion SOP per data type / system",
        "Sample deletion certificates / audit trail",
        "Retention schedule defining 'when to delete'",
        "Cryptographic-erasure procedure",
        "Backup-deletion procedure aligned with retention",
        "DSAR-driven deletion evidence (GDPR Art. 17)",
    ],
    "A.8.11": [
        "Data-masking policy and tooling (Liquibase, Delphix, in-DB masking)",
        "Sample masked dataset used in lower environments",
        "Tokenisation / pseudonymisation architecture for sensitive fields",
        "Data-flow diagram annotated with masking points",
        "Sample non-prod environment seed showing no PII",
    ],
    "A.8.12": [
        "DLP policy + console configuration (Microsoft Purview, Forcepoint, Netskope)",
        "DLP incident report sample with disposition",
        "Channels covered: email, web, endpoint, cloud-API",
        "Watermarking / fingerprinting evidence on critical IP",
        "Quarantine / release workflow",
        "Trend metrics (DLP incidents per quarter)",
    ],
    "A.8.13": [
        "Backup policy (frequency, retention, encryption, offsite)",
        "Latest backup verification / restore-test evidence",
        "Backup encryption configuration",
        "Immutable / air-gapped backup evidence (ransomware-resilience)",
        "Coverage metric (% protected systems with valid recent backup)",
        "Failed-backup alerting configuration",
        "Annual DR exercise restoring from backup",
    ],
    "A.8.14": [
        "High-availability architecture diagrams",
        "Failover test evidence (chaos drill, region-failover, AZ-failover)",
        "RTO/RPO compliance metric from last test",
        "Load-balancer / HA-cluster configuration screenshots",
        "Active-active vs active-passive design rationale",
    ],
    "A.8.15": [
        "Logging standard (sources, fields, retention, format)",
        "SIEM / log-platform dashboard showing live ingestion",
        "Source-coverage list (OS, IAM, network, cloud audit, app)",
        "Log-retention policy + storage configuration",
        "Log-integrity controls (WORM, hash, signing)",
        "Sample successful evidence-retrieval for an investigation",
    ],
    "A.8.16": [
        "Detection-engineering catalogue (sigma/KQL rules with owners)",
        "Use-case coverage matrix mapped to MITRE ATT&CK",
        "Mean-Time-to-Detect metric over last 90 days",
        "Alert-tuning log (false-positive reduction efforts)",
        "On-call / SOC schedule",
        "Sample escalation from alert to incident",
    ],
    "A.8.17": [
        "NTP / PTP configuration on critical hosts",
        "Drift-monitoring alert configuration",
        "Authoritative time sources documented",
        "Sample time-deviation alert + resolution",
        "Coverage metric (% hosts within ±tolerance of authoritative time)",
    ],
    "A.8.18": [
        "List of privileged utilities (sudo, registry editor, db admin tools) and access controls",
        "Audit logs of utility usage",
        "Approval workflow for installing such utilities",
        "Compensating monitoring on systems where utilities cannot be removed",
        "Periodic review of who has privileged-utility access",
    ],
    "A.8.19": [
        "Software-installation policy (allow-listed apps, package signing)",
        "Endpoint allow-list configuration (AppLocker, WDAC, jamf)",
        "Change-control evidence for production software installs",
        "Software-bill-of-materials per critical system",
        "Detection rule for unauthorised software-install attempts",
    ],
    "A.8.20": [
        "Network security architecture diagrams",
        "Firewall ruleset export with last review date",
        "Network-segmentation evidence (VLAN, micro-seg, ZTNA)",
        "Egress filtering / web proxy configuration",
        "Rule-base cleanup metric (% unused / shadowed rules)",
        "Wireless network security configuration",
    ],
    "A.8.21": [
        "SLAs with network-service providers",
        "Monitoring of provider service availability",
        "DDoS-mitigation configuration / vendor contract",
        "BGP / DNS protection (e.g. RPKI, DNSSEC)",
        "Sample ISP-incident handling record",
    ],
    "A.8.22": [
        "Network-segmentation diagram (zones, micro-segmentation, VLANs)",
        "Firewall-rule audit showing inter-zone restrictions",
        "Sample East-West traffic policy",
        "DMZ design doc and review",
        "Cloud VPC peering / transit gateway configuration",
        "Penetration test confirming segmentation effectiveness",
    ],
    "A.8.23": [
        "Web-filter / Secure-Web-Gateway configuration (category blocks, SSL inspection)",
        "Filter-bypass / exception register",
        "User awareness on filter rationale",
        "Threat-feed integration (categorisation freshness)",
        "Metric: blocked sessions per quarter by category",
    ],
    "A.8.24": [
        "Cryptography policy (approved algorithms, key lengths, deprecations)",
        "KMS / HSM configuration evidence",
        "Certificate inventory and rotation schedule",
        "PKI procedures (CA hierarchy, revocation)",
        "TLS configuration scan output (SSL Labs grade)",
        "Crypto-agility plan (post-quantum readiness, weak-cipher retirement)",
        "Key-ceremony records for high-trust roots",
    ],
    "A.8.25": [
        "Secure SDLC policy and gate definitions (threat-model, SAST, DAST, SCA, pentest)",
        "SDLC gate evidence from a recent release",
        "Definition of Done including security criteria",
        "Security-champion programme records",
        "Threat-modelling artefacts for critical apps",
        "CI pipeline screenshots showing security stages",
    ],
    "A.8.26": [
        "Application security requirements doc per app",
        "Threat-model artefact (e.g. STRIDE) for a critical app",
        "Abuse-case definitions",
        "OWASP ASVS / SAMM mapping",
        "Sample requirements traceability matrix",
    ],
    "A.8.27": [
        "Architecture review board records",
        "Reference architecture / engineering principles doc",
        "Sample architecture-review minutes for a new project",
        "Architectural-decision records (ADRs)",
        "Sign-off evidence for critical-design approvals",
    ],
    "A.8.28": [
        "Secure coding standard (per language)",
        "SAST scan report from CI for a recent build",
        "Code-review checklist including security items",
        "Linter / security plugin configuration (Semgrep, CodeQL)",
        "Developer secure-coding training records",
        "Pre-commit hook configuration",
    ],
    "A.8.29": [
        "Test plan including security tests (auth, authz, injection, secrets)",
        "Acceptance criteria sign-off including security",
        "Pentest report from most recent release",
        "DAST scan reports against staging",
        "Performance / load test results (security-relevant: rate-limit, DDoS resilience)",
        "Bug-bash / security demo records",
    ],
    "A.8.30": [
        "Outsourcing security requirements (clauses, on-prem audit rights)",
        "Vendor SDLC questionnaire response",
        "Source-code escrow arrangement (where relevant)",
        "Code-quality requirements imposed on outsource partner",
        "Build pipeline / artefact verification evidence",
    ],
    "A.8.31": [
        "Environment-separation architecture (network, IAM, data)",
        "Promotion process / change-control records",
        "Sample CR / approval for a prod deployment",
        "Test-data policy (no production data; or anonymised pull)",
        "Production-access control evidence",
        "Drift-detection between environments",
    ],
    "A.8.32": [
        "Change-management policy + tool screenshots (ServiceNow / Jira CR)",
        "Sample standard / normal / emergency change tickets",
        "Emergency-change retroactive-approval workflow",
        "Backout-plan template + sample completed",
        "Change-Advisory-Board (CAB) minutes",
        "Failed-change rate metric",
    ],
    "A.8.33": [
        "Test-data policy (no production data; or anonymised pull procedure)",
        "Sample anonymisation / synthetic-data pipeline output",
        "Test-data retention and destruction SOP",
        "Detection of accidental prod-data presence in non-prod",
        "Tooling list: faker / synth / data-masking",
    ],
    "A.8.34": [
        "Audit-testing scope and rules-of-engagement doc",
        "Backup taken before destructive audit testing",
        "Read-only credentials issued for auditors",
        "Monitoring of auditor-access activity",
        "Post-audit cleanup verification",
    ],
}


# ---------------------------------------------------------------------------
# NIST CSF 2.0 — informative-reference style hints
# ---------------------------------------------------------------------------

NIST_CSF_2_0_EVIDENCE: dict[str, list[str]] = {
    # GV.OC ----
    "GV.OC-01": [
        "Mission / vision statement tying business objectives to cybersecurity outcomes",
        "Business-strategy doc with cybersecurity considerations called out",
        "Board-level acknowledgement of cyber as a strategic enabler",
        "Translation of mission into security priorities (e.g. annual cyber objectives)",
        "Cross-functional alignment minutes (security ↔ business)",
    ],
    "GV.OC-02": [
        "Stakeholder map (customers, regulators, partners, employees) with security expectations",
        "Customer-facing security statements (trust centre, SOC2 / ISO certificates)",
        "Regulatory engagement log",
        "Investor / shareholder reporting on cyber",
        "Employee survey results on security culture",
    ],
    "GV.OC-03": [
        "Register of applicable laws / regulations / contracts and their owners",
        "Compliance attestation evidence (SOC2, ISO certificate, …)",
        "Legal review log for new regulations",
        "Contractual security commitments tracker",
        "Privacy notice / customer terms",
    ],
    "GV.OC-04": [
        "Mission-essential capabilities list with dependency map",
        "Business Impact Analysis (BIA) covering critical services",
        "RTO/RPO matrix per critical service",
        "Stakeholder expectation documentation (SLAs, OLAs)",
        "Customer-impact severity matrix",
    ],
    "GV.OC-05": [
        "Third-party dependency inventory (cloud, SaaS, payroll, identity)",
        "Critical-supplier criticality tiering",
        "Inter-organisational dependency map",
        "Service-mesh / API dependency catalogue",
        "Last review of supplier-dependency risks",
    ],
    # GV.RM ----
    "GV.RM-01": [
        "Risk management objectives doc approved by leadership",
        "Risk committee charter",
        "Annual risk-management programme plan",
        "Stakeholder sign-off evidence",
        "Alignment doc between cyber-risk and enterprise objectives",
    ],
    "GV.RM-02": [
        "Risk appetite statement signed by board / exec",
        "Quantitative tolerances (e.g. max $X loss, max Y hours downtime)",
        "Per-domain risk thresholds (cyber, privacy, compliance)",
        "Sample escalation when tolerance exceeded",
        "Annual appetite review minutes",
    ],
    "GV.RM-03": [
        "ERM framework showing cyber-risk integration",
        "Joint cyber + ERM risk register sample",
        "Common taxonomy and scoring methodology",
        "Quarterly ERM-committee minutes covering cyber",
        "Integrated risk-reporting dashboard",
    ],
    "GV.RM-04": [
        "Risk-response taxonomy (accept / transfer / mitigate / avoid) policy",
        "Sample risk-treatment plans for top risks",
        "Insurance / cyber-insurance evidence (for transfer)",
        "Risk-acceptance approval workflow",
        "Effectiveness review of past treatments",
    ],
    "GV.RM-05": [
        "Risk reporting cadence to leadership / board (minutes, slides)",
        "Defined escalation thresholds",
        "Sample escalation event",
        "Communication channels for risk reporting",
        "Risk-information classification policy",
    ],
    "GV.RM-06": [
        "Risk scoring methodology (e.g. FAIR, NIST 800-30) doc",
        "Risk register showing consistent scoring across entries",
        "Calibration / training evidence for risk assessors",
        "Risk-aggregation method for portfolio view",
        "Comparison of inherent vs residual risk",
    ],
    "GV.RM-07": [
        "Risk-vs-opportunity analysis sample (new product / market)",
        "Strategic-opportunity framework",
        "Innovation pipeline with risk-opportunity assessment",
        "Documented trade-off analyses",
    ],
    # GV.RR ----
    "GV.RR-01": [
        "Board-level cybersecurity accountability statement",
        "Exec performance objectives mentioning cyber outcomes",
        "Charter showing leadership ownership of cyber risk",
        "Sample board minutes discussing cyber",
        "Reporting line from CISO to board / audit committee",
    ],
    "GV.RR-02": [
        "RACI for security responsibilities",
        "Job descriptions for security roles",
        "Org chart with security function placement",
        "Authority delegation matrix for security decisions",
        "Cross-functional security responsibilities (HR, Legal, IT)",
    ],
    "GV.RR-03": [
        "Approved security budget for current year",
        "Headcount plan for security function",
        "Tooling / licence procurement evidence",
        "Training / professional development budget",
        "Vendor / consultant budget for security work",
    ],
    "GV.RR-04": [
        "HR policies referencing security (BG checks, training, disciplinary, offboarding)",
        "HR-security joint process docs",
        "Sample joint-investigation procedure",
        "HR training on security policies",
        "Coordination evidence on policy-violation cases",
    ],
    # GV.PO ----
    "GV.PO-01": [
        "Approved enterprise cybersecurity policy with sign-off",
        "Policy distribution / acknowledgement records",
        "Communication evidence (email blast, training, all-hands)",
        "Enforcement procedures + sample enforcement actions",
        "Topic-specific sub-policies (AUP, BCP, IR, …)",
    ],
    "GV.PO-02": [
        "Policy review log (annual at minimum)",
        "Diff between policy versions tied to threat / regulatory changes",
        "Stakeholder review feedback evidence",
        "Communication of policy updates",
        "Effectiveness review of policy implementation",
    ],
    # GV.OV ----
    "GV.OV-01": [
        "Cyber KPI / KRI report (patch SLA, MTTD/MTTR, training rates, incidents)",
        "Management Review minutes addressing outcomes",
        "Trend dashboard over multiple periods",
        "Action items from review and closure evidence",
        "Strategy-adjustment evidence based on outcomes",
    ],
    "GV.OV-02": [
        "Strategy review report covering coverage gaps vs threat landscape",
        "Annual strategy refresh doc",
        "External-input review (intel, industry trends)",
        "Strategy traceability to identified risks",
        "Stakeholder consultation evidence",
    ],
    "GV.OV-03": [
        "Performance review of risk-management activities (audit findings, KPI trends)",
        "Improvement actions tracked to closure",
        "Independent assessment / maturity review report",
        "Lessons-learned aggregation",
        "Benchmark / peer-comparison data",
    ],
    # GV.SC ----
    "GV.SC-01": [
        "Cyber supply-chain risk management programme document",
        "C-SCRM responsibility / RACI",
        "Programme scope (which suppliers, which risks)",
        "Annual programme review",
        "Tooling for supplier monitoring (SecurityScorecard, BitSight)",
    ],
    "GV.SC-02": [
        "Supplier security contractual roles defined",
        "Joint security-responsibility matrix",
        "Standard security exhibit in supplier contracts",
        "Sample DPA / DPAg for a major supplier",
        "Escalation contacts at suppliers",
    ],
    "GV.SC-03": [
        "Joint cyber + ERM risk register including supplier risks",
        "ERM-committee minutes covering supplier risk",
        "Supplier-risk methodology integrated with ERM",
        "Aggregated supplier-risk reporting",
        "Cross-functional supplier-risk governance",
    ],
    "GV.SC-04": [
        "Supplier inventory ranked by criticality",
        "Criteria used to determine criticality",
        "Coverage metric (% supplier-base inventoried)",
        "Last review / refresh date",
        "Critical-supplier sub-tier dependencies (4th parties)",
    ],
    "GV.SC-05": [
        "Standard security clauses for supplier contracts",
        "Vendor security questionnaire template",
        "Standard breach-notification clauses",
        "Audit-rights clauses",
        "Sub-contractor / 4th-party clauses",
    ],
    "GV.SC-06": [
        "Vendor onboarding due-diligence checklist (security review, SOC2/ISO cert review)",
        "Sample completed vendor security review",
        "Risk-tiering decision evidence",
        "Pre-contract pentest / assessment results (for high-risk vendors)",
        "Procurement-veto evidence (vendors not approved due to security)",
    ],
    "GV.SC-07": [
        "Continuous vendor monitoring report (SecurityScorecard / BitSight / similar)",
        "Quarterly supplier-risk review minutes",
        "Sample issue raised with a supplier",
        "Trend report over multiple quarters",
        "Top-supplier deep-dive review",
    ],
    "GV.SC-08": [
        "Vendor IR plan (joint incident contact, escalation)",
        "Tabletop exercise involving a major supplier",
        "Communication-tree including suppliers",
        "Sample post-incident review including supplier",
        "Recovery planning incorporating supplier inputs",
    ],
    "GV.SC-09": [
        "Vendor performance scorecard including security metrics",
        "Trend report over multiple quarters",
        "Periodic reassessment evidence",
        "Action items resulting from supplier reviews",
        "Vendor-improvement plan samples",
    ],
    "GV.SC-10": [
        "Exit / termination procedure for supplier engagements",
        "Last data-return / data-destruction certificate from a terminated vendor",
        "Off-boarding checklist",
        "Knowledge-transfer evidence",
        "Sample contract termination evidence",
    ],

    # ID.AM ----
    "ID.AM-01": [
        "Hardware CMDB export with owner, location, serial, criticality",
        "Reconciliation between MDM / network scan / CMDB",
        "Asset-registration SOP",
        "Quarterly inventory-audit results",
        "Coverage metric (% hardware with owner populated)",
        "Discovery scan output (e.g. Lansweeper, Tenable Discovery)",
    ],
    "ID.AM-02": [
        "Software inventory (per-host SBOM or asset agent)",
        "Service catalogue with owners",
        "Approved-software allow-list",
        "Shadow-IT detection output (CASB / endpoint reports)",
        "SaaS-license inventory",
        "Coverage metric (% endpoints reporting software inventory)",
    ],
    "ID.AM-03": [
        "Network data-flow diagrams (internal + external)",
        "Approved data-flow register",
        "East-west traffic visibility evidence (flow logs, NDR)",
        "Egress-flow monitoring",
        "API / integration catalogue",
        "Last review / refresh of data-flow docs",
    ],
    "ID.AM-04": [
        "Supplier inventory cross-referenced to ID.AM-01/02",
        "Subprocessor list (relevant for SaaS)",
        "Critical-supplier service catalogue",
        "Contractual list of services per supplier",
        "Change-tracking when supplier scope changes",
    ],
    "ID.AM-05": [
        "Asset criticality matrix mapping assets → business impact",
        "Asset prioritisation review log",
        "Tiering rubric (Tier 1 / 2 / 3)",
        "Coverage metric (% critical assets identified and tagged)",
        "Sample resource-allocation decision based on criticality",
    ],
    "ID.AM-07": [
        "Data inventory / data map (by data type, location, owner, retention)",
        "Privacy register (RoPA, Article 30 GDPR)",
        "Data-classification scheme + assignment evidence",
        "Sensitive-data discovery scan output (e.g. Microsoft Purview)",
        "Cross-border data-flow inventory",
    ],
    "ID.AM-08": [
        "Asset-lifecycle SOP (acquire → operate → decommission)",
        "Decommissioning records",
        "Secure-disposal certificates",
        "End-of-life / end-of-support inventory",
        "Replacement planning evidence",
    ],
    # ID.RA ----
    "ID.RA-01": [
        "Latest vulnerability-scan report",
        "Patch / mitigation tracking ticket queue",
        "SLA-compliance metric per severity",
        "Scanner coverage report (% assets scanned)",
        "False-positive review evidence",
        "Manual vulnerability-research records",
    ],
    "ID.RA-02": [
        "Threat-intel platform feed subscriptions",
        "Periodic intel briefings",
        "ISAC / industry forum membership",
        "Sample intel summary disseminated",
        "Intel-to-detection feedback loop documentation",
    ],
    "ID.RA-03": [
        "Threat-modelling artefacts for critical systems",
        "Threat register with internal + external categories",
        "MITRE ATT&CK mapping for prioritised techniques",
        "Insider-threat assessment evidence",
        "Geopolitical / sector-specific threat analysis",
    ],
    "ID.RA-04": [
        "Risk assessment showing likelihood × impact per scenario",
        "Methodology doc (FAIR, NIST 800-30)",
        "Scenarios analysed with input data",
        "Quantitative loss-expectancy calculations",
        "Calibration / consistency evidence across assessors",
    ],
    "ID.RA-05": [
        "Inherent-vs-residual risk register",
        "Risk-response prioritisation rationale",
        "Top-N risks list for current period",
        "Risk-aggregation view for leadership",
        "Trend over time per top risk",
    ],
    "ID.RA-06": [
        "Risk-treatment plans with owners and target dates",
        "Status report on open treatments",
        "Treatment-effectiveness review evidence",
        "Communication of treatment decisions",
        "Sample treatment closure with verification",
    ],
    "ID.RA-07": [
        "Change-management tickets including risk-impact field",
        "Exception register with expiry and compensating controls",
        "Sample emergency-change with risk re-assessment",
        "Risk-impact assessment template for changes",
        "Change-failure rate metric",
    ],
    "ID.RA-08": [
        "Vulnerability disclosure policy (security.txt, bug-bounty page)",
        "Sample handled vulnerability submission",
        "Disclosure-handling SOP",
        "Response-SLA metric",
        "Bug-bounty programme report (if applicable)",
    ],
    "ID.RA-09": [
        "Hardware / software acquisition checklist (authenticity verification)",
        "Code-signing / hash-verification SOP for downloads",
        "Tamper-evident packaging procedures (for hardware)",
        "Sample verification record (signed receipt of authenticity)",
        "Anti-counterfeit measures",
    ],
    "ID.RA-10": [
        "Vendor security questionnaire results (pre-contract)",
        "Independent attestations (SOC 2, ISO 27001 certificate) collected",
        "Risk-tier-driven assessment depth",
        "Sample veto evidence (vendor not approved)",
        "Pre-acquisition pentest results (for high-risk acquisitions)",
    ],
    # ID.IM ----
    "ID.IM-01": [
        "Improvement log following internal / external assessments",
        "Audit-findings remediation tracker",
        "Sample assessment outcome + improvement actions",
        "Effectiveness verification of improvements",
        "Periodic improvement-review meetings",
    ],
    "ID.IM-02": [
        "Tabletop / red-team / DR exercise reports",
        "Action items closed-loop tracking",
        "Exercise schedule (annual cadence)",
        "Sample exercise scenario doc",
        "Participation evidence (attendance, roles played)",
    ],
    "ID.IM-03": [
        "Operations retro / postmortem records (security and non-security)",
        "Process change history tied to retros",
        "Lessons-learned register",
        "Continuous-improvement metric (improvements per quarter)",
        "Sample updated runbook after a retro",
    ],
    "ID.IM-04": [
        "Incident-response plan and recovery / continuity plans (versioned)",
        "Plan review evidence (annual + post-incident)",
        "Plan distribution / training records",
        "Plan-test outcomes from exercises",
        "Sign-off by leadership on plan updates",
    ],

    # PR.AA ----
    "PR.AA-01": [
        "IAM lifecycle SOP (joiner / mover / leaver)",
        "Identity store inventory (AD, Okta, Azure AD, AWS IAM, …)",
        "Service-account inventory with owner + purpose",
        "Workload-identity policy (e.g. SPIFFE, AWS IRSA)",
        "Sample provisioning ticket",
        "Coverage metric (HR → IAM sync timeliness)",
    ],
    "PR.AA-02": [
        "Identity-proofing procedure (e.g. IAL2 for high-risk roles)",
        "Sample onboarding identity-verification artefacts",
        "Document-verification tooling configuration",
        "Step-up verification procedure for sensitive roles",
        "Customer / partner identity-proofing approach",
    ],
    "PR.AA-03": [
        "MFA enforcement report (100% for admin, % for user)",
        "Service-account authentication evidence (workload identity / mTLS)",
        "Phishing-resistant MFA rollout status (FIDO2, certificate-based)",
        "Authentication-policy doc",
        "Risk-based / adaptive auth configuration",
        "Failed-auth alerting + sample triage",
    ],
    "PR.AA-04": [
        "SAML / OIDC signing certificate inventory + rotation log",
        "Token-lifetime / refresh-policy configuration",
        "Assertion attribute mapping documentation",
        "Sample assertion / token (decoded, redacted)",
        "Audit log of identity-assertion verifications",
    ],
    "PR.AA-05": [
        "Role-to-permission matrix per system",
        "Access-recertification report",
        "Just-in-time / privilege-elevation configuration",
        "Periodic least-privilege review evidence",
        "Sample access-request approval workflow",
        "Coverage metric (% systems with documented role model)",
    ],
    "PR.AA-06": [
        "Physical access control system (badge / biometric) configuration",
        "Visitor log + escort SOP",
        "Periodic access-list audit",
        "Tailgating-prevention mechanisms",
        "Sample badge-deactivation at separation",
        "CCTV coverage at controlled-area entries",
    ],
    # PR.AT ----
    "PR.AT-01": [
        "Annual awareness-training completion-rate report",
        "Phishing simulation campaign results + trend",
        "Onboarding security induction completion log",
        "Content topics covered (phishing, password, data, IR)",
        "Effectiveness measure (click-rate, quiz pass-rate)",
        "Communication materials (intranet, newsletter, posters)",
    ],
    "PR.AT-02": [
        "Role-based training for devs (secure coding), admins (privileged access), finance (BEC)",
        "Training attendance / certification records",
        "Specialised certifications maintained (CISSP, CEH, etc.)",
        "Vendor-specific training (AWS Security, Azure, GCP)",
        "Career-development tracks for security roles",
    ],
    # PR.DS ----
    "PR.DS-01": [
        "Encryption-at-rest evidence (disk, database, S3 SSE-KMS) — config screenshots",
        "Key-management system audit log sample",
        "Encryption-key rotation schedule + recent rotation log",
        "Sensitive-data discovery + encryption-coverage metric",
        "Cryptographic algorithm / key-length compliance",
        "Backup / archive encryption evidence",
    ],
    "PR.DS-02": [
        "TLS enforcement evidence (config, scanner output e.g. SSL Labs A+)",
        "Internal-traffic encryption (service-mesh mTLS) config",
        "Certificate-rotation automation evidence (cert-manager / ACM)",
        "Outdated-protocol scan results (TLS 1.0/1.1 absent)",
        "VPN / ZTNA configuration for remote access",
        "Email-in-transit encryption (TLS MTA-MTA)",
    ],
    "PR.DS-10": [
        "Enclave / confidential-compute usage evidence (SGX, Nitro Enclaves)",
        "Memory-protection / tokenisation evidence for sensitive processing",
        "Tokenisation service configuration",
        "Sensitive-field masking in logs",
        "Application-memory hardening evidence (ASLR, DEP)",
    ],
    "PR.DS-11": [
        "Backup policy + last successful restore test report",
        "Backup encryption configuration",
        "Immutable / air-gapped backup evidence",
        "Coverage metric (% systems with valid recent backup)",
        "Failed-backup alerting configuration",
        "Annual DR exercise restoring from backup",
    ],
    # PR.PS ----
    "PR.PS-01": [
        "Configuration baselines (CIS, vendor-STIG) by platform",
        "Compliance scanner output (CIS-CAT, AWS Config)",
        "Drift-detection alerts and remediation evidence",
        "Golden-image / IaC-template repo",
        "Change-control evidence for baseline updates",
    ],
    "PR.PS-02": [
        "Patch-management SLA + compliance dashboard",
        "EOL software register and replacement plan",
        "Sample patched-vs-unpatched metric per environment",
        "Critical-patch fast-track procedure",
        "Application-update automation evidence",
    ],
    "PR.PS-03": [
        "Hardware refresh schedule",
        "Decommissioning records with secure-disposal certs",
        "Firmware update procedure + evidence",
        "EOL-hardware inventory",
        "Asset-lifecycle KPI (% within supported lifespan)",
    ],
    "PR.PS-04": [
        "Logging standard + SIEM source-coverage",
        "SIEM ingestion dashboard / retention configuration",
        "Critical-system log-collection verification",
        "Log-integrity controls (WORM, hashing)",
        "Sample missing-log alert + remediation",
        "Cloud-audit log coverage (CloudTrail, Azure Activity, GCP Audit)",
    ],
    "PR.PS-05": [
        "Application allow-list config (AppLocker / WDAC / jamf)",
        "Detection rule for unauthorised binary execution",
        "Sample blocked-execution event",
        "Bypass / exception register",
        "Endpoint script-control configuration",
    ],
    "PR.PS-06": [
        "Secure SDLC policy + CI security-gate evidence",
        "SAST / SCA / IaC-scan reports for recent build",
        "Threat-modelling artefacts",
        "Pentest report from most recent release",
        "Definition of Done including security criteria",
        "Security-champion programme records",
    ],
    # PR.IR ----
    "PR.IR-01": [
        "Network segmentation diagram + firewall ruleset",
        "Zero-trust / micro-segmentation configuration evidence",
        "Egress filtering configuration",
        "Sample lateral-movement detection rule",
        "VPN / ZTNA enforcement evidence",
        "Penetration test confirming segmentation effectiveness",
    ],
    "PR.IR-02": [
        "Environmental controls (UPS, HVAC, fire-suppression) inspection reports",
        "Site risk assessment",
        "Power-redundancy testing evidence",
        "Cooling-redundancy testing evidence",
        "Fire-suppression test certificates",
    ],
    "PR.IR-03": [
        "High-availability architecture diagrams (multi-AZ, DR site)",
        "Recent failover / chaos exercise report",
        "RTO/RPO compliance metric from last test",
        "Load-balancer / HA-cluster configuration",
        "Active-active vs active-passive design rationale",
    ],
    "PR.IR-04": [
        "Capacity planning report",
        "Auto-scaling policies (cloud) screenshots",
        "Capacity-threshold alerting",
        "Trend over multiple quarters",
        "Sample capacity-related incident postmortem",
    ],

    # DE.CM ----
    "DE.CM-01": [
        "Network IDS / NDR configuration",
        "Sample detection alerts and response logs",
        "Flow-log collection evidence",
        "Anomaly-detection tuning records",
        "Coverage map showing monitored network segments",
        "DNS / HTTP monitoring configuration",
    ],
    "DE.CM-02": [
        "Physical security monitoring (CCTV, intrusion, badge anomaly) configs",
        "Sample physical-alert investigations",
        "After-hours-access monitoring",
        "Door-forced-open alerting",
        "Tailgating-detection evidence",
    ],
    "DE.CM-03": [
        "UEBA / user-monitoring configuration",
        "Privileged-session recording sample",
        "Insider-threat detection rules",
        "Sample anomalous-user-behaviour alert",
        "Privacy / disclosure notice for monitoring",
    ],
    "DE.CM-06": [
        "Third-party / SaaS log ingestion into SIEM (Okta, GitHub, Salesforce, …)",
        "Vendor activity alerts",
        "API-call monitoring for integrations",
        "OAuth-app inventory + access monitoring",
        "Sample anomalous-vendor-action alert",
    ],
    "DE.CM-09": [
        "EDR / cloud workload protection (CWPP) coverage report",
        "Sample alert + investigation",
        "Runtime-protection configuration (e.g. Falco, GuardDuty)",
        "Container / Kubernetes security monitoring",
        "Serverless function monitoring",
        "Database-activity monitoring (DAM)",
    ],
    # DE.AE ----
    "DE.AE-02": [
        "Analyst playbooks per alert type",
        "Sample triaged alerts with notes",
        "Investigation case-management tooling",
        "Quality-review sample (last 20 alerts re-checked)",
        "Pattern / TTP catalogue used by analysts",
    ],
    "DE.AE-03": [
        "SIEM correlation rules / aggregation views",
        "Sample multi-source correlated incident",
        "Threat-graph / link-analysis usage",
        "Data-normalisation evidence (CIM, OCSF)",
        "Cross-tool integration documentation",
    ],
    "DE.AE-04": [
        "Incident scoring rubric (severity matrix)",
        "Sample scored incidents and rationale",
        "Impact-assessment template",
        "Asset-value × incident-severity calculation",
        "Customer-impact estimation procedure",
    ],
    "DE.AE-06": [
        "SOC distribution lists / paging integrations",
        "Sample case notifications to stakeholders",
        "Incident-status dashboards",
        "Automated notification rules",
        "Escalation paths documented",
    ],
    "DE.AE-07": [
        "Threat-intel enrichment in SIEM/SOAR",
        "Sample enriched alert with TI context",
        "IoC matching evidence",
        "Contextual asset / identity enrichment",
        "Sample geo / WHOIS / sandbox enrichment",
    ],
    "DE.AE-08": [
        "Incident-declaration criteria doc",
        "Sample declared incident with timestamp + rationale",
        "Decision authority for declaration",
        "Trigger-event matrix",
        "Quality review of declaration consistency",
    ],

    # RS.MA ----
    "RS.MA-01": [
        "Incident-response plan",
        "Sample exec record of plan execution during a real incident",
        "IR coordination evidence with third parties (CSP, vendor)",
        "Customer / regulator communication tracker",
        "Plan-activation criteria",
        "Roles activated during last incident",
    ],
    "RS.MA-02": [
        "Triage SOP + queue evidence",
        "Sample false-positive vs true-positive reclassification",
        "Validation criteria for reports",
        "Initial-response timing metric",
        "Cross-team triage handoff procedure",
    ],
    "RS.MA-03": [
        "Incident-categorisation taxonomy (malware, account compromise, data leak)",
        "Sample categorised cases",
        "Severity-mapping rubric",
        "Priority queue evidence",
        "Trend metrics by category",
    ],
    "RS.MA-04": [
        "Escalation matrix with named contacts + SLAs",
        "Sample escalated case",
        "Authority levels documented",
        "After-hours escalation procedure",
        "External-resource activation criteria (IR retainer, law enforcement)",
    ],
    "RS.MA-05": [
        "Recovery-initiation criteria doc",
        "Sample case showing recovery decision recorded",
        "Containment-vs-recovery decision framework",
        "Stakeholder approval for recovery",
        "Risk assessment before recovery initiation",
    ],
    # RS.AN ----
    "RS.AN-03": [
        "Forensic timeline doc from a recent incident",
        "Root-cause analysis (5-whys / fishbone)",
        "Attack-vector identification evidence",
        "Lateral-movement reconstruction",
        "Impact-determination evidence",
    ],
    "RS.AN-06": [
        "Chain-of-custody form sample",
        "Forensic workstation imaging SOP",
        "Evidence-vault access control",
        "Investigator training / certification records",
        "Hash-verification of all collected evidence",
    ],
    "RS.AN-07": [
        "Evidence-collection SOP (logs, memory, disk)",
        "Hash-verification log",
        "Tool inventory (FTK, EnCase, Volatility, KAPE)",
        "Sample collection record",
        "Court-admissibility considerations doc",
    ],
    "RS.AN-08": [
        "Impact-assessment template",
        "Sample completed assessment with affected-data counts",
        "Affected-asset enumeration evidence",
        "Customer-impact quantification",
        "Regulatory-notification-threshold check",
    ],
    # RS.CO ----
    "RS.CO-02": [
        "Notification matrix (regulators, customers, partners) with timeframes",
        "Sample notification record",
        "Notification templates per audience",
        "Legal / PR review workflow for notifications",
        "Compliance with mandatory disclosure timelines (GDPR 72h, NIS2, SEC)",
    ],
    "RS.CO-03": [
        "Information-sharing SOP (with ISAC, CERT)",
        "Sample shared indicator / report",
        "TLP usage evidence",
        "Sharing-approval workflow",
        "Receipt of intel from sharing partners",
    ],
    # RS.MI ----
    "RS.MI-01": [
        "Containment playbooks per incident type",
        "Sample case showing containment actions and timestamps",
        "Network-isolation procedures",
        "Account-disablement evidence",
        "Sample short-term containment vs long-term containment",
    ],
    "RS.MI-02": [
        "Eradication SOP (remediation, rebuild, credential reset)",
        "Sample eradication confirmation log",
        "Rebuild-from-known-good evidence",
        "Persistence-removal verification",
        "Post-eradication validation (clean scan)",
    ],

    # RC.RP ----
    "RC.RP-01": [
        "Recovery plan integrated into IRP",
        "Sample case showing recovery phase initiation",
        "RTO / RPO targets per service",
        "Authority for recovery initiation",
        "Coordination with operations / business teams",
    ],
    "RC.RP-02": [
        "Recovery prioritisation matrix",
        "Sample recovery action list with owners",
        "Service-dependency mapping",
        "Communication of recovery sequence",
        "Sample milestone tracker",
    ],
    "RC.RP-03": [
        "Backup-integrity verification log",
        "Restore test reports",
        "Cryptographic-checksum evidence on backups",
        "Sample malware-scan of backup before restore",
        "Air-gapped backup verification",
    ],
    "RC.RP-04": [
        "Post-incident operating-norms doc",
        "Sample updated runbook after an incident",
        "Compensating-control evidence during recovery",
        "Risk-acceptance for residual issues during recovery",
        "Communication to staff on operating norms",
    ],
    "RC.RP-05": [
        "Restoration-verification checklist + sign-off",
        "Service-restoration evidence (monitoring graphs)",
        "Data-integrity verification post-restore",
        "Customer-confirmation of restored service",
        "Functional / smoke-test results",
    ],
    "RC.RP-06": [
        "Incident-closure criteria doc",
        "Sample incident closure record + final report",
        "Stakeholder sign-off on closure",
        "Documentation completeness check",
        "Transition to lessons-learned phase",
    ],
    # RC.CO ----
    "RC.CO-03": [
        "Recovery-status communication templates",
        "Sample stakeholder updates during recovery",
        "Internal status-update cadence evidence",
        "External-stakeholder communication log",
        "Communication-channel selection rationale",
    ],
    "RC.CO-04": [
        "Public-statement template + legal/PR approval workflow",
        "Sample statement from a past incident",
        "Press-release distribution evidence",
        "Social-media response procedure",
        "Customer-FAQ template",
    ],
}


# ---------------------------------------------------------------------------
# Public lookup
# ---------------------------------------------------------------------------

BUILT_IN_EVIDENCE_HINTS: dict[str, dict[str, list[str]]] = {
    "urn:cyberguard:framework:iso-27001-2022": ISO_27001_2022_EVIDENCE,
    "urn:cyberguard:framework:nist-csf-2.0": NIST_CSF_2_0_EVIDENCE,
}
