"""Pydantic schemas package."""
from app.schemas.auth import (
    LoginRequest,
    TokenResponse,
    TokenPayload,
    RefreshTokenRequest,
    RegisterRequest,
    PasswordChangeRequest,
    PasswordResetRequest,
    SetPasswordRequest,
)
from app.schemas.user import (
    UserBase,
    UserCreate,
    UserUpdate,
    UserResponse,
    UserListResponse,
)
from app.schemas.agent import (
    AgentConfigBase,
    AgentConfigCreate,
    AgentConfigUpdate,
    AgentConfigRead,
    AgentConfigListResponse,
    AgentTestResponse,
    AgentExecutionRead,
)
from app.schemas.skill import (
    SkillBase,
    SkillCreate,
    SkillUpdate,
    SkillResponse,
    SkillListResponse,
    ToolBase,
    ToolCreate,
    ToolUpdate,
    ToolResponse,
)
from app.schemas.knowledge import (
    KnowledgeBaseBase,
    KnowledgeBaseCreate,
    KnowledgeBaseUpdate,
    KnowledgeBaseResponse,
    KnowledgeBaseListResponse,
    DocumentBase,
    DocumentCreate,
    DocumentUpdate,
    DocumentResponse,
    DocumentUploadResponse,
    KnowledgeQueryRequest,
    KnowledgeQueryResponse,
)
from app.schemas.chat import (
    ChatMessageRequest,
    ChatMessageResponse,
    ChatSessionResponse,
    IntentParsingRequest,
    IntentParsingResponse,
    GroupChatCreateRequest,
    GroupChatMessageRequest,
    GroupChatResponse,
    GroupChatRoundResponse,
    AgentChatRequest,
    AgentChatResponse,
)
from app.schemas.task import (
    TaskPriority,
    TaskStatus,
    TaskBase,
    TaskCreate,
    TaskUpdate,
    TaskResponse,
    TaskListResponse,
    TaskExecuteRequest,
    TaskExecuteResponse,
)
from app.schemas.schedule import (
    ScheduleBase,
    ScheduleCreate,
    ScheduleUpdate,
    ScheduleResponse,
    ScheduleExecutionResponse,
    ScheduleListResponse,
)
from app.schemas.audit import (
    AuditLogResponse,
    AuditLogListResponse,
    AuditLogQuery,
    AuditLogExportRequest,
)
from app.schemas.backup import (
    BackupConfigBase,
    BackupConfigCreate,
    BackupConfigUpdate,
    BackupConfigResponse,
    BackupExecutionResponse,
    RestoreRequest,
    RestoreResponse,
    BackupListResponse,
)
from app.schemas.config import (
    ConfigValueUpdate,
    ConfigSectionResponse,
    LLMProviderConfig,
    LLMProviderUpdate,
    SystemConfigResponse,
    FeatureFlagsResponse,
)
from app.schemas.provider import (
    ProviderBase,
    ProviderCreate,
    ProviderUpdate,
    ProviderResponse,
    ProviderListResponse,
    ProviderTestRequest,
    ProviderTestResponse,
)
from app.schemas.mcp import (
    MCPServerBase,
    MCPServerCreate,
    MCPServerUpdate,
    MCPServerResponse,
    MCPToolBase,
    MCPToolCreate,
    MCPToolResponse,
    MCPToolExecuteRequest,
    MCPToolExecuteResponse,
    MCPServerListResponse,
)
from app.schemas.groupchat import (
    GroupChatMessageResponse,
    GroupChatSessionResponse,
    GroupChatCreateRequest,
    GroupChatAddMessageRequest,
    GroupChatRunRoundRequest,
    GroupChatRunToCompletionRequest,
    GroupChatRoundResponse,
    GroupChatCancelRequest,
)

__all__ = [
    # Auth
    "LoginRequest",
    "TokenResponse",
    "TokenPayload",
    "RefreshTokenRequest",
    "RegisterRequest",
    "PasswordChangeRequest",
    "PasswordResetRequest",
    "SetPasswordRequest",
    # User
    "UserBase",
    "UserCreate",
    "UserUpdate",
    "UserResponse",
    "UserListResponse",
    # Agent
    "AgentConfigBase",
    "AgentConfigCreate",
    "AgentConfigUpdate",
    "AgentConfigRead",
    "AgentConfigListResponse",
    "AgentTestResponse",
    "AgentExecutionRead",
    # Skill
    "SkillBase",
    "SkillCreate",
    "SkillUpdate",
    "SkillResponse",
    "SkillListResponse",
    "ToolBase",
    "ToolCreate",
    "ToolUpdate",
    "ToolResponse",
    # Knowledge
    "KnowledgeBaseBase",
    "KnowledgeBaseCreate",
    "KnowledgeBaseUpdate",
    "KnowledgeBaseResponse",
    "KnowledgeBaseListResponse",
    "DocumentBase",
    "DocumentCreate",
    "DocumentUpdate",
    "DocumentResponse",
    "DocumentUploadResponse",
    "KnowledgeQueryRequest",
    "KnowledgeQueryResponse",
    # Chat
    "ChatMessageRequest",
    "ChatMessageResponse",
    "ChatSessionResponse",
    "IntentParsingRequest",
    "IntentParsingResponse",
    "GroupChatCreateRequest",
    "GroupChatMessageRequest",
    "GroupChatResponse",
    "GroupChatRoundResponse",
    "AgentChatRequest",
    "AgentChatResponse",
    # Task
    "TaskPriority",
    "TaskStatus",
    "TaskBase",
    "TaskCreate",
    "TaskUpdate",
    "TaskResponse",
    "TaskListResponse",
    "TaskExecuteRequest",
    "TaskExecuteResponse",
    # Schedule
    "ScheduleBase",
    "ScheduleCreate",
    "ScheduleUpdate",
    "ScheduleResponse",
    "ScheduleExecutionResponse",
    "ScheduleListResponse",
    # Audit
    "AuditLogResponse",
    "AuditLogListResponse",
    "AuditLogQuery",
    "AuditLogExportRequest",
    # Backup
    "BackupConfigBase",
    "BackupConfigCreate",
    "BackupConfigUpdate",
    "BackupConfigResponse",
    "BackupExecutionResponse",
    "RestoreRequest",
    "RestoreResponse",
    "BackupListResponse",
    # Config
    "ConfigValueUpdate",
    "ConfigSectionResponse",
    "LLMProviderConfig",
    "LLMProviderUpdate",
    "SystemConfigResponse",
    "FeatureFlagsResponse",
    # Provider
    "ProviderBase",
    "ProviderCreate",
    "ProviderUpdate",
    "ProviderResponse",
    "ProviderListResponse",
    "ProviderTestRequest",
    "ProviderTestResponse",
    # MCP
    "MCPServerBase",
    "MCPServerCreate",
    "MCPServerUpdate",
    "MCPServerResponse",
    "MCPToolBase",
    "MCPToolCreate",
    "MCPToolResponse",
    "MCPToolExecuteRequest",
    "MCPToolExecuteResponse",
    "MCPServerListResponse",
    # GroupChat
    "GroupChatMessageResponse",
    "GroupChatSessionResponse",
    "GroupChatCreateRequest",
    "GroupChatAddMessageRequest",
    "GroupChatRunRoundRequest",
    "GroupChatRunToCompletionRequest",
    "GroupChatRoundResponse",
    "GroupChatCancelRequest",
]